
# Oracle Local#
server.port=8081
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=system
spring.datasource.password=123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.connection-timeout: 30000
spring.datasource.hikari.minimum-idle: 10
spring.datasource.hikari.max-lifetime: 120000
spring.datasource.hikari.maximum-pool-size: 15
spring.datasource.hikari.idle-timeout: 35000

# JPA #
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
logging.level.org.hibernate.SQL=debug

##KEYCLOAK LOCAL
#keycloak.issuer=http://localhost:8080/realms/ejemplo1
#keycloak.base-uri=http://localhost:8080/auth/realms/
#keycloak.authorization-uri=http://localhost:8080/realms/ejemplo1/protocol/openid-connect/auth
#keycloak.user-info-uri=http://localhost:8080/realms/ejemplo1/protocol/openid-connect/userinfo
#keycloak.token-uri=http://localhost:8080/realms/ejemplo1/protocol/openid-connect/token
#keycloak.logout=http://localhost:8080/realms/ejemplo1/protocol/openid-connect/logout
#keycloak.jwk-set-uri=http://localhost:8080/realms/ejemplo1/protocol/openid-connect/certs
#keycloak.client-id=front-ejemplo-1

keycloak.issuer=http://localhost:8080/realms/demo
keycloak.base-uri=http://localhost:8080/auth/realms/
keycloak.authorization-uri=http://localhost:8080/realms/demo/protocol/openid-connect/auth
keycloak.user-info-uri=http://localhost:8080/realms/demo/protocol/openid-connect/userinfo
keycloak.token-uri=http://localhost:8080/realms/demo/protocol/openid-connect/token
keycloak.logout=http://localhost:8080/realms/demo/protocol/openid-connect/logout
keycloak.certs=http://localhost:8080/realms/demo/protocol/openid-connect/certs
keycloak.client-id=seguridad-demo
keycloak.scope=profile
keycloak.authorization-grant-type=password
keycloak.authorization-grant-type-refresh=refresh_token
jwt.auth.converter.attribute-name=preferred_username
logging.level.org.keycloak=DEBUG

# ARCHIVOS
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

eureka.client.enabled=false
app.storage.location=mediafile

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=1800000

# application.properties
#server.servlet.encoding.charset=UTF-8
#server.servlet.encoding.enabled=true
#server.servlet.encoding.force=true

#PROFILES
#spring.profiles.active=prod

#LOG
#logging.level.root=INFO
#logging.level.org.springframework=WARN
#logging.level.com.yourproject=DEBUG
#logging.level.org.hibernate=ERROR
#logging.file.name=logs/appSeguridad.log
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n



#ORIGINS URLS
allowed.cors.origins=http://localhost:4200