# Oracle Desarrollo#
server.port=1025
spring.datasource.url=jdbc:oracle:thin:@zsrv004:1998:bcrdesa
spring.datasource.username=bcrp_msauthentica_api
spring.datasource.password=bcrp_msauthentica_api
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.sql.init.mode=always

spring.datasource.hikari.connection-timeout: 30000
spring.datasource.hikari.minimum-idle: 10
spring.datasource.hikari.max-lifetime: 120000
spring.datasource.hikari.maximum-pool-size: 15
spring.datasource.hikari.idle-timeout: 35000

# JPA #
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
logging.level.org.hibernate.SQL=debug


##KEYCLOAK DESARROLLO
keycloak.issuer=http://172.30.107.211:443/realms/demo
keycloak.base-uri=http://172.30.107.211:443/auth/realms/
keycloak.authorization-uri=http://172.30.107.211:443/realms/demo/protocol/openid-connect/auth
keycloak.user-info-uri=http://172.30.107.211:443/realms/demo/protocol/openid-connect/userinfo
keycloak.token-uri=http://172.30.107.211:443/realms/demo/protocol/openid-connect/token
keycloak.logout=http://172.30.107.211:443/realms/demo/protocol/openid-connect/logout
keycloak.jwk-set-uri=http://172.30.107.211:443/realms/demo/protocol/openid-connect/certs
keycloak.client-id=seguridad-demo


keycloak.authorization-grant-type=password
keycloak.authorization-grant-type-refresh=refresh_token

logging.level.org.keycloak=DEBUG

##ARCHIVOS#
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

eureka.client.enabled=false

app.storage.location=mediafile

# Redis Configuration
spring.data.redis.host=172.30.107.212
spring.data.redis.port=6379
spring.cache.type=redis
#spring.cache.redis.time-to-live=1800000

#ORIGINS URLS
allowed.cors.origins=http://localhost:4200