# Oracle Desarrollo#
server.port=${SERVER_PORT}
#SID DEV
spring.datasource.url=jdbc:oracle:thin:@${ORACLE_HOST}:${ORACLE_PORT}:${ORACLE_SID}
#SERVICE NAME LOCAL
#spring.datasource.url=jdbc:oracle:thin:@${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_SERVICE_NAME}
spring.datasource.username=${BD_USERNAME}
spring.datasource.password=${BD_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.sql.init.mode=always
spring.jpa.properties.hibernate.default_schema=BCRP_MSAUTHENTICA_API

spring.datasource.hikari.connection-timeout: 30000
spring.datasource.hikari.minimum-idle: 10
spring.datasource.hikari.max-lifetime: 120000
spring.datasource.hikari.maximum-pool-size: 15
spring.datasource.hikari.idle-timeout: 35000

# JPA #
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
#logging.level.org.hibernate.SQL=debug


##KEYCLOAK DESARROLLO
keycloak.issuer=${KEYCLOAK_ISSUER}
keycloak.base-uri=${KEYCLOAK_BASE_URI}
keycloak.authorization-uri=${KEYCLOAK_AUTH_URI}
keycloak.user-info-uri=${KEYCLOAK_INFO_URI}
keycloak.token-uri=${KEYCLOAK_TOKEN_URI}
keycloak.logout=${KEYCLOAK_LOGOUT}
keycloak.certs=${KEYCLOAK_CERTS}
keycloak.client-id=${KEYCLOAK_CLIENT_ID}
keycloak.scope=profile
keycloak.authorization-grant-type=password
keycloak.authorization-grant-type-refresh=refresh_token
jwt.auth.converter.attribute-name=preferred_username
logging.level.org.keycloak=DEBUG

##ARCHIVOS#
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

eureka.client.enabled=false
app.storage.location=mediafile


#LOG
logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.com.yourproject=DEBUG
logging.level.org.hibernate=ERROR
logging.file.name=logs/appSeguridad.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# REDIS CONFIGURACION
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.cache.type=redis
#spring.cache.redis.time-to-live=1800000


#JAVA-MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rwongsol@gmail.com
spring.mail.password=dnmg xsae eunf nbqg
spring.mail.properties.mail.smtp.starttls.enable = true

#ORIGINS URLS
allowed.cors.origins=${ALLOWED_CORS_ORIGINS}

