version: '3.8'

services:
  app:
    image: app-service-seguridad:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      ORACLE_HOST: ${ORACLE_HOST}
      ORACLE_PORT: ${ORACLE_PORT}
      ORACLE_SERVICE_NAME: ${ORACLE_SERVICE_NAME}
      BD_USERNAME: ${BD_USERNAME}
      BD_PASSWORD: ${BD_PASSWORD}
      KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER}
      KEYCLOAK_BASE_URI: ${KEYCLOAK_BASE_URI}
      KEYCLOAK_AUTH_URI: ${KEYCLOAK_AUTH_URI}
      KEYCLOAK_INFO_URI: ${KEYCLOAK_INFO_URI}
      KEYCLOAK_TOKEN_URI: ${KEYCLOAK_TOKEN_URI}
      KEYCLOAK_LOGOUT: ${KEYCLOAK_LOGOUT}
      KEYCLOAK_CERTS: ${KEYCLOAK_CERTS}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      ALLOWED_CORS_ORIGINS: ${ALLOWED_CORS_ORIGINS}
    depends_on:
      - oracle
      - redis

  #oracle:
  #  image: gvenzl/oracle-xe:21-slim
  #  environment:
  #    ORACLE_PASSWORD: 123
  #    APP_USER: system
  #  ports:
  #    - "1521:1521"

  #redis:
  #  image: redis:6.0
  #  ports:
  #    - "6379:6379"
